"""initial schema

Revision ID: 2148dfe10783
Revises:
Create Date: 2026-09-27 14:22:59.211011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2148dfe10783"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required for the booking overlap exclusion constraint: the equality
    # operator (area_id =) inside a GiST index comes from btree_gist.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condominiums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email_contact", sa.String(length=254), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_cpf"), "people", ["cpf"], unique=True)
    op.create_table(
        "account_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("condominium_id", "name", name="uq_account_category_per_condominium"),
    )
    op.create_index(
        op.f("ix_account_categories_condominium_id"),
        "account_categories",
        ["condominium_id"],
        unique=False,
    )
    op.create_table(
        "common_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_common_areas_condominium_id"), "common_areas", ["condominium_id"], unique=False
    )
    op.create_table(
        "pets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("species", sa.String(length=50), nullable=False),
        sa.Column("breed", sa.String(length=100), nullable=True),
        sa.Column("resident_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resident_id"], ["people.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pets_condominium_id"), "pets", ["condominium_id"], unique=False)
    op.create_index("ix_pets_resident_id", "pets", ["resident_id"], unique=False)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("block", sa.String(length=50), nullable=True),
        sa.Column("unit_type", sa.String(length=30), nullable=False),
        sa.Column("fraction", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("condominium_id", "code", name="uq_unit_code_per_condominium"),
    )
    op.create_index("ix_units_condominium_id", "units", ["condominium_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_global_admin", sa.Boolean(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "period",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(start_at, end_at)", persisted=True),
            nullable=False,
            comment="Generated tstzrange(start_at, end_at) — enforced by exclusion constraint",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("area_id"), "="),
            (sa.column("period"), "&&"),
            where=sa.text("status = 'reserved'"),
            using="gist",
            name="uq_bookings_no_overlap",
        ),
        sa.CheckConstraint("end_at > start_at", name="ck_bookings_end_after_start"),
        sa.ForeignKeyConstraint(["area_id"], ["common_areas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_area_id"), "bookings", ["area_id"], unique=False)
    op.create_index("ix_bookings_area_start", "bookings", ["area_id", "start_at"], unique=False)
    op.create_index("ix_bookings_condominium_id", "bookings", ["condominium_id"], unique=False)
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["account_categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_entries_category_id", "entries", ["category_id"], unique=False)
    op.create_index(op.f("ix_entries_condominium_id"), "entries", ["condominium_id"], unique=False)
    op.create_index(
        "ix_entries_condominium_period", "entries", ["condominium_id", "date"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("condominium_id", "unit_id", "period", name="uq_invoice_unit_period"),
    )
    op.create_index(
        op.f("ix_invoices_condominium_id"), "invoices", ["condominium_id"], unique=False
    )
    op.create_index("ix_invoices_period", "invoices", ["condominium_id", "period"], unique=False)
    op.create_table(
        "member_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "unit_id", "role", name="uq_member_link"),
    )
    op.create_index("ix_member_links_person_id", "member_links", ["person_id"], unique=False)
    op.create_index(op.f("ix_member_links_unit_id"), "member_links", ["unit_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "condominium_id", name="uq_membership_user_condominium"),
    )
    op.create_index(
        op.f("ix_memberships_condominium_id"), "memberships", ["condominium_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "parking_spots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("identifier", sa.String(length=50), nullable=False),
        sa.Column("spot_type", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "condominium_id", "identifier", name="uq_parking_identifier_per_condominium"
        ),
    )
    op.create_index(
        "ix_parking_spots_condominium_id", "parking_spots", ["condominium_id"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condominium_id", sa.Integer(), nullable=False),
        sa.Column("plate", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("resident_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["condominium_id"], ["condominiums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resident_id"], ["people.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("condominium_id", "plate", name="uq_vehicle_plate_per_condominium"),
    )
    op.create_index(
        op.f("ix_vehicles_condominium_id"), "vehicles", ["condominium_id"], unique=False
    )
    op.create_index("ix_vehicles_resident_id", "vehicles", ["resident_id"], unique=False)
    op.create_table(
        "entry_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "unit_id", name="uq_entry_allocation_unit"),
    )
    op.create_index(
        op.f("ix_entry_allocations_entry_id"), "entry_allocations", ["entry_id"], unique=False
    )
    op.create_index("ix_entry_allocations_unit_id", "entry_allocations", ["unit_id"], unique=False)
    op.create_table(
        "membership_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["membership_id"], ["memberships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("membership_id", "role", name="uq_membership_role"),
    )
    op.create_index(
        op.f("ix_membership_roles_membership_id"),
        "membership_roles",
        ["membership_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "paid_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("recorded_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recorded_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_membership_roles_membership_id"), table_name="membership_roles")
    op.drop_table("membership_roles")
    op.drop_index("ix_entry_allocations_unit_id", table_name="entry_allocations")
    op.drop_index(op.f("ix_entry_allocations_entry_id"), table_name="entry_allocations")
    op.drop_table("entry_allocations")
    op.drop_index("ix_vehicles_resident_id", table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_condominium_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_parking_spots_condominium_id", table_name="parking_spots")
    op.drop_table("parking_spots")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_condominium_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_member_links_unit_id"), table_name="member_links")
    op.drop_index("ix_member_links_person_id", table_name="member_links")
    op.drop_table("member_links")
    op.drop_index("ix_invoices_period", table_name="invoices")
    op.drop_index(op.f("ix_invoices_condominium_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_entries_condominium_period", table_name="entries")
    op.drop_index(op.f("ix_entries_condominium_id"), table_name="entries")
    op.drop_index("ix_entries_category_id", table_name="entries")
    op.drop_table("entries")
    op.drop_index("ix_bookings_condominium_id", table_name="bookings")
    op.drop_index("ix_bookings_area_start", table_name="bookings")
    op.drop_index(op.f("ix_bookings_area_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_units_condominium_id", table_name="units")
    op.drop_table("units")
    op.drop_index("ix_pets_resident_id", table_name="pets")
    op.drop_index(op.f("ix_pets_condominium_id"), table_name="pets")
    op.drop_table("pets")
    op.drop_index(op.f("ix_common_areas_condominium_id"), table_name="common_areas")
    op.drop_table("common_areas")
    op.drop_index(op.f("ix_account_categories_condominium_id"), table_name="account_categories")
    op.drop_table("account_categories")
    op.drop_index(op.f("ix_people_cpf"), table_name="people")
    op.drop_table("people")
    op.drop_table("condominiums")
    # ### end Alembic commands ###
